pipeline {
    agent any
   
    stages { 
       
        stage('拉取仓库代码') {
            steps {
               
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Qixuan-lab/test.git']])
                echo '拉取git的仓库代码 - SUCCESS'
            }
        }
        stage('通过maven构建项目') {
            steps {
                echo '通过maven构建项目-SUCCESS '
            }
        }

        stage('通过SonarQube进行代码的质量检测') {
            steps {
                echo '通过SonarQube进行代码的检测-SUCCESS '
            }
        }

        stage('通过Docker进行构建自定义镜') {
            steps {
                echo '通过Docker进行构建自定义镜像-SUCCESS '
            }
        }

        stage('将镜像推送到harbor镜像仓库') {
            steps {
                echo '将镜像推送到harbor镜像仓库-SUCCESS'
            }
        }
        stage('通知Publisher over SSH 通知目标服务器') {
            steps {
                echo '通知Publisher over SSH 通知目标服务器-SUCCESS'
            }
        }
    } // 结束 stages
} // 结束 pipeline