pipeline {
    agent any
   
    stages { 
       
        stage('拉取仓库代码') {
            steps {
               
                checkout scmGit(branches: [[name: '$tag']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Qixuan-lab/test.git']])
                echo '拉取git的仓库代码 - SUCCESS'
            }
        }
        stage('通过maven构建项目') {
            steps {
               dir('demo') {
                 sh '/var/jenkins_home/maven/bin/mvn clean package -DskipTests'
                }
               echo '通过maven构建项目-SUCCESS '
            }
        }

        stage('通过SonarQube进行代码的质量检测') {
            steps {
                sh '/var/jenkins_home/sonar-scanner/bin/sonar-scanner -Dsonar.source=./demo -Dsonar.projectname=${JOB_NAME} -Dsonar.projectKey=${JOB_NAME} -Dsonar.java.binaries=./demo/target/  -Dsonar.sourceEncoding=UTF-8 -Dsonar.login=8b6df009ba4f9410ca051ad2e6f7586201cc38e4'
                echo '通过SonarQube进行代码的检测-SUCCESS '
            }
        }

        stage('通过Docker进行构建自定义镜') {
            steps {
                sh '''mv ./demo/target/*.jar  ./demo/docker  
                docker build  -t  ${JOB_NAME}:${tag} ./demo/docker  '''
                echo '通过Docker进行构建自定义镜像-SUCCESS '
            }
        }

        stage('将镜像推送到harbor镜像仓库') {
            steps {
                echo '将镜像推送到harbor镜像仓库-SUCCESS'
            }
        }
        stage('通知Publisher over SSH 通知目标服务器') {
            steps {
                echo '通知Publisher over SSH 通知目标服务器-SUCCESS'
            }
        }
    } // 结束 stages
} // 结束 pipeline
